### ISSUE TITLE
Realtek 8812 packetloss

### ISSUE THREAD

**Issue by rodizio1** [RespawnDespair/wifibroadcast-image-builder#65] opened 2018-11-16 10:15 UTC
I still have the same issue as reported here: https://github.com/aircrack-ng/rtl8812au/issues/116 with the latest image with Kernel 4.14.71 and Realtek driver 5.2.20.

**Comment by RespawnDespair** [comment] 2018-11-16 10:18
I'm not sure what i can fix regarding this.
Unless the aircrack group comes up with a better driver i don't think we'll see improvements...

**Comment by Yes21** [comment] 2018-11-16 13:09
I'm trying to test the v5.3.4 branch, which should be very promising. Devs have just ad the possibility to compile it on RPI (https://github.com/aircrack-ng/rtl8812au/issues/180#issuecomment-439117599).
I've follow @RespawnDespair's instructions and they work, but kernel modules are not compiled.
I don't give up, and will tell you when it will work ...

**Comment by Yes21** [comment] 2018-11-16 18:17
I can't succeed in building an image with v5.3.4 !
The `.../realtek/Kconfig + Makefile` and the `.../realtek/rtl8812au/Makefile` are well patched, but the kernel module is never compiled (I can't see any error message).
I attach here the patch file I did :
[linux-4.14-Makefile-5.3.4.txt](https://github.com/RespawnDespair/wifibroadcast-image-builder/files/2590412/linux-4.14-Makefile-5.3.4.txt)
If somebody wants to check if I did a mistake ?

**Comment by Yes21** [comment] 2018-11-18 20:49
I could compile the 5.3.4 8812au driver without any problem on a regular 2018-10-09-raspbian-stretch-lite image.

But with our script builded image I can't succeed in installing it or making it work !

1- I didn't succeed in creating the good patch for getting it compiling by the script ...

2- I did compile it with the "normal" way (make / make install), but the 88XXau.ko module refused to be loaded (modprobe: ERROR: could not insert '88XXau': Exec format error).

I think I know the reason of the 2nd problem (kernel header version ...).
I will create a new issue about this problem, I already had when trying to install 5.2.20.

**Comment by RespawnDespair** [comment] 2018-11-19 14:46
So no need to redo everything in the builder for 5.3.4 right now?

**Comment by pilotnbr1** [comment] 2018-11-19 16:55
So what’s everyone’s feeling on this issue? Is it a matter of waiting till better updated drivers come out? Is this something best put on the side for a later version of EZ?

**Comment by rodizio1** [comment] 2018-11-19 17:02
Right now, all I can tell is, that the packetloss issue also occurs with the 5.3.4 branch, so upgrading to that branch won't solve that issue.

I'm not sure what branch is "better" for us, in general, I'd say let's go with the latest version unless there is something speaking against that.

I think it's important to fix this problem for both the other RTL8812/14 adapters also, since the Ralink and Atheros cards are becoming hard to find, we need good Realtek support.

**Comment by Yes21** [comment] 2018-11-19 17:49
I think 5.2.20 is good enough for the next EZ-WBC version. There are not so many packetloss, and it doesn't affect 8814 ...
But we'll have to find an easy way to be able to test other 8812/14 driver version, without having to change building scripts/patches.
One should be able to compile a new version like on a regular raspbian-strech-lite.

**Comment by dposea** [comment] 2018-11-20 01:41
The best way to test is to have one person build and distribute modules that you can load with insmod . The kernel versions etc. should be the same if the same version of wbc image is used.  I think you should go with the 5.3.4 version as the top devs all seem to think the code they included from realtek was much better than the collected code used in 5.2.20. I have an AWUS1900 that the vid/pid says is actually from edimax. Should I get an AWUS036ACH for testing also? Is the 036  an 8812 chip? The vid/pid on my 1900 is 0x0bd9/0x8813 but it uses the 8814 driver.

**Comment by dposea** [comment] 2018-11-20 05:57
steps I took to compile
sent rtl8812au-5.3.4.zip from aircrack github to SD card
sent linux-headers-4.14.71-1.ARCH.tar.xz to SD card

booted rpi
used tar -xvf *.tar.xz to extract headers. These were extracted into usr/lib/modules/4.14.71-ARCH/build so I moved them to /usr/src/linux-headers-4.14.71-v7+ 
in /lib/modules/4.14.7`-v7+ removed build and added link
ln -s /usr/src/linux-headers-4.1`4.71-v7+ build 

you should be able to build the rtl8812 driver now.

**Comment by dposea** [comment] 2018-11-20 05:58
I forgot to add eit Makefile to change x386 config to no and rpi config to yes

**Comment by Yes21** [comment] 2018-11-20 09:45
@dposea Many thanks for the help.

Where did you find "linux-headers-4.14.71-1.ARCH.tar.xz" ?

**Comment by RespawnDespair** [comment] 2018-11-20 09:48
While this may work it is not the approach i'd recommend using the image builder.
If we were to decide to use 5.3.4 i will make sure it builds with the image builder itself.
I have however heard several arguments for moving to 5.2.2, and now we are trying 5.3.4 again.
@rodizio1 confirmed neither version is without problems. What would the main benefit be moving to 5.3.4? Other than it being the highest version, is it actually better? If so i will modify the scripts to use this version, otherwise i suggest leaving it at 5.2.2 for now and move on to other aspects of testing and tuning to get the 2.0 beta out.

**Comment by Yes21** [comment] 2018-11-20 13:54
5.3.4 should have better support for 8814 chipset. But I can't confirm that before having tested it.
I'll try to install the driver with @dposea's method ...

**Comment by Yes21** [comment] 2018-11-20 15:55
@dposea 

> Should I get an AWUS036ACH for testing also?
If you don't need a 036ACH, don't buy one only for testing !
The AWUS1900 is better than 036ACH.

> Is the 036 an 8812 chip?
Yes

**Comment by Yes21** [comment] 2018-11-20 17:32
> Only AWUS1900 has 0 packetloss.

@rodizio1 I should add to my [test result](https://www.rcgroups.com/forums/showpost.php?p=40494559&postcount=49) that when I have make the test for the first time, I had as many packet loss with AWUS1900 than with AWUS036ACH. But after having rebooting the groundPi, then I didn't have no more packet loss with AWUS1900 !! I could reproduce it many times today ... 
The groundPi needs always a second boot to show the best results !!

I had observed exactly the same behavior with [uplink telemetry](https://github.com/bortek/EZ-WifiBroadcast/issues/180#issue-379905816) : it never works the first time, but works very well after a second reboot.

I can't understand this behavior ...

But now **I always boot 2 times my groundPi**, and all is working better.

**Comment by Yes21** [comment] 2018-11-22 17:03
> @rodizio1 did test only with AWUS036ACH ...
If I don't see any improvement with AWUS1900 and 5.3.4, I well tell you we have any interest to move to it ...

I finally could try v5.3.4 with AWUS1900, and should say that I could see any difference with 5.2.20.

So there's no need to move to 5.3.4.

**Comment by RespawnDespair** [comment] 2018-11-23 14:42
@Yes21  After reading back on these issues, is it possible you have power wiring problem?
Most of the time booting the second time and having it work is an indication of a serious power supply issue... Are you direct powering the wifi cards?

**Comment by RespawnDespair** [comment] 2018-11-23 15:30
Powering the WiFi adapter from the Pi itself is exactly wrong 😄 
Lots of issues doing it this way, look at the 'proper wiring' in the wiki for some helpfull hints in directly powering the wifi cards.
I do test this way myself, but i accept that delays and issues with connection can occur at times and then reboot.
I have a 'properly wired' setup as well, but with the different wifi dongles and pi's i'm testing now i haven't soldered them all.
Let me know you results when directly powering the pi/wifi dongles. Make sure you get a powerfull BEC. Slightly above 5 volt is also okay.

**Comment by dposea** [comment] 2018-11-24 23:12
I copied  yes21's wiring using the the pi's test pads and have no more power issues, and  nothing has been hurt. I have a couple of pi3s that i cant power via usb since mixing in a 9v power supply one day, but they work via the GPIO pins still. If you dont know the pi's have a weird fuse that can take a day to reset, but it does protect against some simple mistakes.

**Comment by dposea** [comment] 2018-11-24 23:13
I'm sorry, the test pad example wasn't from yes I guess.

**Comment by RespawnDespair** [comment] 2018-11-26 07:53
@rodizio1 Can you confirm any benefits from the 5.3.4?
I'm tempted to move to this anyway, just because it is the 'latest' version.
RTS/CTS could be important, and the devs do say the code is cleaner, so that alone might be worth the effort....

**Comment by rodizio1** [comment] 2018-11-26 14:12
> According to the main air crack devs 5.3.4 is much better code wise than 5.2.0, including code released by realtek. That makes it worth upgrading in my mind. I'm learning about wifi cards slowly so someday I'll understand the drivers. It looks like RTS/CTS is enabled in the 8812 driver. I dont know how to test that.

What I know is, that you have to set radiotap headers to tell the drivers/wifi-card-firmware to generate CTS protection frames.

In the tx_rawsock sources you can see an example for the radiotap headers for the datarate being set:
https://github.com/bortek/EZ-WifiBroadcast/blob/2db9e268a69f86580a1a370678fee67544e836b1/root/wifibroadcast/tx_rawsock.c#L181

For example, the corresponding byte for the datarate in the radiotap header gets set to the hexadecimal value "30" to get a 24mbit datarate:

```
case 24:
		u8aRadiotapHeader[8]=0x30;
```

0x30 hex = 48 decimal. The unit is in 500kbit increments, so a value of 48 sets a datarate of 24 (see here for info about the corresponding radiotap rate field: https://www.radiotap.org/fields/Rate.html)


Now basically, the same has to be done for CTS protection. I'm not sure about the details, but I believe this is the corresponding radiotap flag which has to be set: https://www.radiotap.org/fields/TX%20flags.html

**Comment by Yes21** [comment] 2018-11-26 21:33
@rodizio1 Many thanks for your explanations about CTS frames.

The subject of this issue is **Realtek 8812 packetloss**, but the discussions here did diverge a lot from this subject (I'm partly responsible) ...

The issue of "Realtek 8812 packetloss" is certainly related to the aircrack-ng/8812 driver (as said by Rodizio), and has nothing to do here.

If the subject is now "RTS/CTS protection with 8812", we could close this issue, and continue the discussion [here](https://github.com/bortek/EZ-WifiBroadcast/issues/185) ?

**Comment by Yes21** [comment] 2018-12-05 20:35
@RespawnDespair Please could you close this issue, which is not really related to the building script, nor with EZ-WBC ?

**Comment by RespawnDespair** [comment] 2018-12-06 09:18
True, but still something to keep in mind.
Closing the issue

**Closed by RespawnDespair** 2018-12-06 09:18 UTC
