### ISSUE TITLE
Uname -R in builder

### ISSUE THREAD

**Issue by pilotnbr1** [RespawnDespair/wifibroadcast-image-builder#84] opened 2018-12-01 20:58 UTC
On builder uname -r returns 4.15.0-39-generic.

On live image uname -r is correct

@Yes21 better to start an issue and stay organised! ;)

**Comment by pilotnbr1** [comment] 2018-12-01 21:00
@Yes21 I believe this is just a problem in the cross compiler. I am wonder if we can set uname -r to the correct value somewhere.

**Comment by Yes21** [comment] 2018-12-01 22:18
@pilotnbr1 Yes, I agree with you, it should be a problem caused by the cross compiler.

Now a question :

>On builder uname -r returns 4.15.0-39.

What do you mean for "On builder" ?
For me it means being ssh connected on the running image ...
And in this situation, `uname -r` returns for me "4.14.71" !

If I flash our uploaded raspbian-stretch-lite-20180924.img on a sd card, and boot it into a Pi, and then connect to it via ssh, I don't need to run `apt-get update`.
I can directly install (`apt-get install`) good version of kernel-headers, and all the packages I need.
If I run `apt-get update`, then apt sources are pointing to the latest raspbian version, and the system believes it is in the latest version.
This command has normally to be run only if one wants to "dist-upgrade" the system, and change the version ...

Why do we need to run `apt-get update` in our built image ?
Because without that we can't install many packages we are needed.
Here is certainly the problem ...
Perhaps the apt source-lists are corrupted or incomplete, because of the cross-compiler ??

I hope these thoughts will help giving you a good idea.

For my side, I will continue the investigations tomorrow.

**Comment by pilotnbr1** [comment] 2018-12-02 21:04
So in another attempt to solve this issue I tried to run rpi-update but to update to the version we want.

here is what I ran-

DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install rpi-update
sudo rpi-update c919d632ddc2a88bcb87b7d0cddd61446d1a36bf 

here is the output in terminal from running it-

*** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13545  100 13545    0     0  11087      0  0:00:01  0:00:01 --:--:-- 11459
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Backing up files (this will take a few minutes)
 *** Backing up firmware
 *** Backing up modules 4.15.0-39-generic
#############################################################
This update bumps to rpi-4.14.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=197689
##############################################################
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    177      0 --:--:-- --:--:-- --:--:--   181
100 56.0M    0 56.0M    0     0  1236k      0 --:--:--  0:00:46 --:--:-- 1306k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.14.71+
 *** depmod 4.14.71-v7+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to c919d632ddc2a88bcb87b7d0cddd61446d1a36bf
 *** A reboot is needed to activate the new firmware


And after as a test I ran uname -r 
It still output the 4.15 version.... I am not sure how to interpret the warning above that says a reboot is needed... This is all being cross compiled

**Comment by pilotnbr1** [comment] 2018-12-04 23:31
So in stage 2 / files / .config for the v7 kernel. This one line

CONFIG_DEFCONFIG_LIST="/lib/modules/$UNAME_RELEASE/.config"

I am wondering where it’s pulling this from in the builder. I am wondering if we should hard code $uname_release... Going to bed so hope to try tomorrow

**Comment by RespawnDespair** [comment] 2018-12-05 08:07
i can't shake the feeling it's somehow using the kernel version from the host, i haven't had much time lately to look into it. It should not be needed to change the config in such a way, crosscompiling has been around for quite some time...

**Comment by Yes21** [comment] 2018-12-05 10:35
>  it's somehow using the kernel version from the host

YES, you're right !!
My host has **4.15.0-39-generic**

**Comment by RespawnDespair** [comment] 2018-12-05 10:43
Good, i'm looking into the problems with building this, i'm still not sure, but maybe we can move it all to 02 stage and fix the makefile as i did for the RTL drivers.

**Comment by pilotnbr1** [comment] 2018-12-05 11:16
Kernel version from the host machine? As in what Qemu puts out?

On another tangent (sorry feel like im going 5 different direction at once) I see that
 in stage 2 00-run.sh

after cloning the kernel  the command git checkout is used and then an ssha hash

I think git checkout prefers a commit from the repo. After chasing it down the commit # is

# Get Kernel Commit
GIT_KERNEL_COMMIT="1244bbb3e92135d247e2dddfa6fe5e3e171a9635"

going to try building it this way.

**Comment by Yes21** [comment] 2018-12-05 13:57
@pilotnbr1 

> Are you guys running the builder on pi?

No, I'm running it on a pc with Ubuntu 18.04 + updates.
On this machine :
```
uname -r
4.15.0-39-generic
```
@RespawnDespair 

> but maybe we can move it all to 02 stage and fix the makefile as i did for the RTL drivers.

Please wait a little before changing that ...
I'm searching a solution here : https://github.com/RPi-Distro/pi-gen
And will ask the devs if they know this problem.

**Comment by Yes21** [comment] 2018-12-05 15:54
Perhaps is the solution [here](https://github.com/RPi-Distro/pi-gen/issues/223) ?
But I don't know what to do with the answer !
Hope you will understood it better like me.

**Comment by RespawnDespair** [comment] 2018-12-05 15:58
I do understannd, but it means we have to pass the correct version ourselves to the make process. I'll try it this weekend.

**Comment by Yes21** [comment] 2018-12-05 16:16
Happy that you could understand :-)

**Comment by pilotnbr1** [comment] 2018-12-05 16:50
yep makes sense... Mine has now changed to 4.15.0-42-generic

Cross compiler gonna need some work

**Comment by RespawnDespair** [comment] 2018-12-06 09:23
Well...
The Makefile for the v4l driver starts with:
`KERNELRELEASE	?= `uname -r``
Which basically means we can pass along a command line statement `KERNELRELEASE=whateverwewant` and it should use that in the build.
Using the trick from the raspi group will take some looking into but would keep things generic and clean. 
I'll try to make this work as soon as i have more time.

**Comment by Yes21** [comment] 2018-12-06 09:47
Or you can force the kernel version like this :

`sudo sed -i 's/KERNELRELEASE ?= $(shell uname -r)/KERNELRELEASE ?= 4.14.71-v7+/' Makefile`

**Comment by RespawnDespair** [comment] 2018-12-06 10:40
While technically correct, it is not needed to actually modify the makefile itself.
Passing the build argument as a parameter is better practice.
Also, i want to prevent the hardcoding of the kernel version. This is where the answer from the raspi group comes into play.
Lemme work on it!

**Comment by Yes21** [comment] 2018-12-06 10:43
Ok you're right ...

**Comment by RespawnDespair** [comment] 2018-12-06 10:46
There is no real right or wrong, and this is one nasty issue 😄 
We'll get it working!

**Comment by RespawnDespair** [comment] 2018-12-06 16:11
More as a mental note to myself, for a generic solution, we want to get our information from this file:
http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-10-11/2018-10-09-raspbian-stretch-lite.info

That would allow a totally generic solution to get the correct linux version as wel as the correct uname.

**Comment by RespawnDespair** [comment] 2018-12-07 14:47
I have a new branche which i will merge shortly.
It pulls the info file and gets the SHA1 for the compatible kernel automatically.
It also extracts the kernel version (both regular and -v7).
The two new properties can be used to run the v4l makefile.
I'm closing this issue when i have merged my own PR from the temporary branche.
Then i will approve the PR's regarding the v4l and modify that code to use these new variables.

**Comment by RespawnDespair** [comment] 2018-12-07 16:18
Seems to work great, closing this issue.

There are two new variables available `KERNEL_VERSION` and `KERNEL_VERSION_V7` see the stage 04, `04-run.sh` script for the usecase for V4L

**Closed by RespawnDespair** 2018-12-07 16:18 UTC

**Comment by Yes21** [comment] 2018-12-07 18:05
@RespawnDespair Good job ! Thanks :-)
