### ISSUE TITLE
problems with internal wifihotspot

### ISSUE THREAD

**Issue by dposea** [RespawnDespair/wifibroadcast-image-builder#38] opened 2018-10-23 04:56 UTC
from this script code:
NUM_CARDS=-1
	NICSWL=`ls /sys/class/net | nice grep wlan`

	for NIC in $NICSWL
	do
	    # set MTU to 2304
	    ifconfig $NIC mtu 2304
	    # re-name wifi interface to MAC address
	    NAME=`cat /sys/class/net/$NIC/address`
	    ip link set $NIC name ${NAME//:}
	    let "NUM_CARDS++"
	    #sleep 0.1
	done

	if [ "$NUM_CARDS" == "-1" ]; then
	    echo "ERROR: No wifi cards detected"
	    collect_errorlog
	    sleep 365d
	fi

    if [ "$CAM" == "0" ]; then # only do relay/hotspot stuff if RX
	    # get wifi hotspot card out of the way
	    if [ "$WIFI_HOTSPOT" == "Y" ]; then
			if [ "$WIFI_HOTSPOT_NIC" != "internal" ]; then
				# only configure it if it's there
				if ls /sys/class/net/ | grep -q $WIFI_HOTSPOT_NIC; then
					tmessage -n "Setting up $WIFI_HOTSPOT_NIC for Wifi Hotspot operation.. "
					ip link set $WIFI_HOTSPOT_NIC name wifihotspot0
					ifconfig wifihotspot0 192.168.2.1 up
					tmessage "done!"
					let "NUM_CARDS--"
				else
					tmessage "Wifi Hotspot card $WIFI_HOTSPOT_NIC not found!"
					sleep 0.5
				fi
			else
				# only configure it if it's there
				if ls /sys/class/net/ | grep -q intwifi0; then
					tmessage -n "Setting up intwifi0 for Wifi Hotspot operation.. "
					ip link set intwifi0 name wifihotspot0
					ifconfig wifihotspot0 192.168.2.1 up
					tmessage "done!"
				else
					tmessage "Pi3 Onboard Wifi Hotspot card not found!"
					sleep 0.5
				fi
			fi
	    fi

MTU is limited to 1500, an error message is generate

NICSWL=`ls /sys/class/net | nice grep wlan` we are looking for wlan0 here, it gets renamed, then if WIFI_HOTSPOT_NIC=internal we look for it to be name intwifi0. It works if WIFI_HOTSOT_NIC is set to a MAC address name.

**Comment by RespawnDespair** [comment] 2018-10-23 17:45
I'm not sure what the problem is you are trying to describe?

The internal wifi hotspot works in the last image. Are you referring to some problem when you don't use the internal wifi?

**Comment by Yes21** [comment] 2018-10-23 18:10
I also don't understand the problem !

The internal wifi hotspot is also working for me ...

**Comment by RespawnDespair** [comment] 2018-10-24 11:11
@dposea Can you clarify the issue any further? Else i will close this as it is cluttering the issues that need to be fixed for 1.6 release.

**Comment by RespawnDespair** [comment] 2018-11-04 14:34
Closing this as no updated use case was supplied.

**Closed by RespawnDespair** 2018-11-04 14:34 UTC
